# Data preprocessing & Feature Enginearing

# Data science life cycle

Prob Def.> Data collection> Data preprocessing> Data analysis> Data visualization

# Data preprocessing


Duties u should do this with Data to build the model


1-Tidy format

2-Data cleaning

3-Data transformation

4-Data modeling

5-Data aggregation

6-Data manipulation

Structured Data


1-Numerical

2-Data time

3-Text

4-Categorical 

In [1]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns

In [2]:
df = sns.load_dataset('titanic')
df

survived  pclass     sex   age  sibsp  parch     fare embarked   class  \
0           0       3    male  22.0      1      0   7.2500        S   Third   
1           1       1  female  38.0      1      0  71.2833        C   First   
2           1       3  female  26.0      0      0   7.9250        S   Third   
3           1       1  female  35.0      1      0  53.1000        S   First   
4           0       3    male  35.0      0      0   8.0500        S   Third   
..        ...     ...     ...   ...    ...    ...      ...      ...     ...   
886         0       2    male  27.0      0      0  13.0000        S  Second   
887         1       1  female  19.0      0      0  30.0000        S   First   
888         0       3  female   NaN      1      2  23.4500        S   Third   
889         1       1    male  26.0      0      0  30.0000        C   First   
890         0       3    male  32.0      0      0   7.7500        Q   Third   

       who  adult_male deck  embark_town alive  alone  
0      man        True  NaN  Southampton    no  False  
1    woman       False    C    Cherbourg   yes  False  
2    woman       False  NaN  Southampton   yes   True  
3    woman       False    C  Southampton   yes  False  
4      man        True  NaN  Southampton    no   True  
..     ...         ...  ...          ...   ...    ...  
886    man        True  NaN  Southampton    no   True  
887  woman       False    B  Southampton   yes   True  
888  woman       False  NaN  Southampton    no  False  
889    man        True    C    Cherbourg   yes   True  
890    man        True  NaN   Queenstown    no   True  

[891 rows x 15 columns]

# Missing Data

# Detect

In [3]:
df.isna()

survived  pclass    sex    age  sibsp  parch   fare  embarked  class  \
0       False   False  False  False  False  False  False     False  False   
1       False   False  False  False  False  False  False     False  False   
2       False   False  False  False  False  False  False     False  False   
3       False   False  False  False  False  False  False     False  False   
4       False   False  False  False  False  False  False     False  False   
..        ...     ...    ...    ...    ...    ...    ...       ...    ...   
886     False   False  False  False  False  False  False     False  False   
887     False   False  False  False  False  False  False     False  False   
888     False   False  False   True  False  False  False     False  False   
889     False   False  False  False  False  False  False     False  False   
890     False   False  False  False  False  False  False     False  False   

       who  adult_male   deck  embark_town  alive  alone  
0    False       False   True        False  False  False  
1    False       False  False        False  False  False  
2    False       False   True        False  False  False  
3    False       False  False        False  False  False  
4    False       False   True        False  False  False  
..     ...         ...    ...          ...    ...    ...  
886  False       False   True        False  False  False  
887  False       False  False        False  False  False  
888  False       False   True        False  False  False  
889  False       False  False        False  False  False  
890  False       False   True        False  False  False  

[891 rows x 15 columns]

In [4]:
df.isna().sum()

survived         0
pclass           0
sex              0
age            177
sibsp            0
parch            0
fare             0
embarked         2
class            0
who              0
adult_male       0
deck           688
embark_town      2
alive            0
alone            0
dtype: int64

In [5]:
#pip install sklearn

In [6]:
from sklearn.impute import MissingIndicator

In [7]:
mi=MissingIndicator()

In [8]:
mi.fit(df)
mi.transform(df).sum()

869

In [55]:
df.dropna()

survived  pclass     sex   age  sibsp  parch     fare embarked  class  \
1           1       1  female  38.0      1      0  71.2833        C  First   
3           1       1  female  35.0      1      0  53.1000        S  First   
6           0       1    male  54.0      0      0  51.8625        S  First   
10          1       3  female   4.0      1      1  16.7000        S  Third   
11          1       1  female  58.0      0      0  26.5500        S  First   
..        ...     ...     ...   ...    ...    ...      ...      ...    ...   
871         1       1  female  47.0      1      1  52.5542        S  First   
872         0       1    male  33.0      0      0   5.0000        S  First   
879         1       1  female  56.0      0      1  83.1583        C  First   
887         1       1  female  19.0      0      0  30.0000        S  First   
889         1       1    male  26.0      0      0  30.0000        C  First   

       who  adult_male deck  embark_town alive  alone  M  my_class  
1    woman       False    C    Cherbourg   yes  False  0         0  
3    woman       False    C  Southampton   yes  False  0         0  
6      man        True    E  Southampton    no   True  1         0  
10   child       False    G  Southampton   yes  False  0         2  
11   woman       False    C  Southampton   yes   True  0         0  
..     ...         ...  ...          ...   ...    ... ..       ...  
871  woman       False    D  Southampton   yes  False  0         0  
872    man        True    B  Southampton    no   True  1         0  
879  woman       False    C    Cherbourg   yes  False  0         0  
887  woman       False    B  Southampton   yes   True  0         0  
889    man        True    C    Cherbourg   yes   True  1         0  

[182 rows x 17 columns]

In [10]:
df.dropna(subset=['deck','age'])

survived  pclass     sex   age  sibsp  parch     fare embarked  class  \
1           1       1  female  38.0      1      0  71.2833        C  First   
3           1       1  female  35.0      1      0  53.1000        S  First   
6           0       1    male  54.0      0      0  51.8625        S  First   
10          1       3  female   4.0      1      1  16.7000        S  Third   
11          1       1  female  58.0      0      0  26.5500        S  First   
..        ...     ...     ...   ...    ...    ...      ...      ...    ...   
871         1       1  female  47.0      1      1  52.5542        S  First   
872         0       1    male  33.0      0      0   5.0000        S  First   
879         1       1  female  56.0      0      1  83.1583        C  First   
887         1       1  female  19.0      0      0  30.0000        S  First   
889         1       1    male  26.0      0      0  30.0000        C  First   

       who  adult_male deck  embark_town alive  alone  
1    woman       False    C    Cherbourg   yes  False  
3    woman       False    C  Southampton   yes  False  
6      man        True    E  Southampton    no   True  
10   child       False    G  Southampton   yes  False  
11   woman       False    C  Southampton   yes   True  
..     ...         ...  ...          ...   ...    ...  
871  woman       False    D  Southampton   yes  False  
872    man        True    B  Southampton    no   True  
879  woman       False    C    Cherbourg   yes  False  
887  woman       False    B  Southampton   yes   True  
889    man        True    C    Cherbourg   yes   True  

[184 rows x 15 columns]

# Imputation

In [11]:
df['age'].fillna(value=round(df['age'].mean()))

0      22.0
1      38.0
2      26.0
3      35.0
4      35.0
       ... 
886    27.0
887    19.0
888    30.0
889    26.0
890    32.0
Name: age, Length: 891, dtype: float64

In [12]:
df['age'].fillna(value=round(df['age'].max()))

0      22.0
1      38.0
2      26.0
3      35.0
4      35.0
       ... 
886    27.0
887    19.0
888    80.0
889    26.0
890    32.0
Name: age, Length: 891, dtype: float64

In [13]:
from sklearn.impute import SimpleImputer

In [14]:
si=SimpleImputer(strategy='mean')

In [15]:
si.fit_transform(df[['age']])

array([[22.        ],
       [38.        ],
       [26.        ],
       [35.        ],
       [35.        ],
       [29.69911765],
       [54.        ],
       [ 2.        ],
       [27.        ],
       [14.        ],
       [ 4.        ],
       [58.        ],
       [20.        ],
       [39.        ],
       [14.        ],
       [55.        ],
       [ 2.        ],
       [29.69911765],
       [31.        ],
       [29.69911765],
       [35.        ],
       [34.        ],
       [15.        ],
       [28.        ],
       [ 8.        ],
       [38.        ],
       [29.69911765],
       [19.        ],
       [29.69911765],
       [29.69911765],
       [40.        ],
       [29.69911765],
       [29.69911765],
       [66.        ],
       [28.        ],
       [42.        ],
       [29.69911765],
       [21.        ],
       [18.        ],
       [14.        ],
       [40.        ],
       [27.        ],
       [29.69911765],
       [ 3.        ],
       [19.        ],
       [29

In [16]:
df[['age']]

age
0    22.0
1    38.0
2    26.0
3    35.0
4    35.0
..    ...
886  27.0
887  19.0
888   NaN
889  26.0
890  32.0

[891 rows x 1 columns]

# Duplication


In [17]:
#Detect duplicated()
#Dropping


In [18]:
# detection

In [19]:
df.duplicated().sum()

107

In [20]:
#dropping

In [21]:
df.drop_duplicates()

survived  pclass     sex   age  sibsp  parch     fare embarked  class  \
0           0       3    male  22.0      1      0   7.2500        S  Third   
1           1       1  female  38.0      1      0  71.2833        C  First   
2           1       3  female  26.0      0      0   7.9250        S  Third   
3           1       1  female  35.0      1      0  53.1000        S  First   
4           0       3    male  35.0      0      0   8.0500        S  Third   
..        ...     ...     ...   ...    ...    ...      ...      ...    ...   
885         0       3  female  39.0      0      5  29.1250        Q  Third   
887         1       1  female  19.0      0      0  30.0000        S  First   
888         0       3  female   NaN      1      2  23.4500        S  Third   
889         1       1    male  26.0      0      0  30.0000        C  First   
890         0       3    male  32.0      0      0   7.7500        Q  Third   

       who  adult_male deck  embark_town alive  alone  
0      man        True  NaN  Southampton    no  False  
1    woman       False    C    Cherbourg   yes  False  
2    woman       False  NaN  Southampton   yes   True  
3    woman       False    C  Southampton   yes  False  
4      man        True  NaN  Southampton    no   True  
..     ...         ...  ...          ...   ...    ...  
885  woman       False  NaN   Queenstown    no  False  
887  woman       False    B  Southampton   yes   True  
888  woman       False  NaN  Southampton    no  False  
889    man        True    C    Cherbourg   yes   True  
890    man        True  NaN   Queenstown    no   True  

[784 rows x 15 columns]

In [22]:
df[df.duplicated()]

survived  pclass     sex   age  sibsp  parch     fare embarked   class  \
47          1       3  female   NaN      0      0   7.7500        Q   Third   
76          0       3    male   NaN      0      0   7.8958        S   Third   
77          0       3    male   NaN      0      0   8.0500        S   Third   
87          0       3    male   NaN      0      0   8.0500        S   Third   
95          0       3    male   NaN      0      0   8.0500        S   Third   
..        ...     ...     ...   ...    ...    ...      ...      ...     ...   
870         0       3    male  26.0      0      0   7.8958        S   Third   
877         0       3    male  19.0      0      0   7.8958        S   Third   
878         0       3    male   NaN      0      0   7.8958        S   Third   
884         0       3    male  25.0      0      0   7.0500        S   Third   
886         0       2    male  27.0      0      0  13.0000        S  Second   

       who  adult_male deck  embark_town alive  alone  
47   woman       False  NaN   Queenstown   yes   True  
76     man        True  NaN  Southampton    no   True  
77     man        True  NaN  Southampton    no   True  
87     man        True  NaN  Southampton    no   True  
95     man        True  NaN  Southampton    no   True  
..     ...         ...  ...          ...   ...    ...  
870    man        True  NaN  Southampton    no   True  
877    man        True  NaN  Southampton    no   True  
878    man        True  NaN  Southampton    no   True  
884    man        True  NaN  Southampton    no   True  
886    man        True  NaN  Southampton    no   True  

[107 rows x 15 columns]

In [23]:
df[df.duplicated(subset=['age','sex'])]

survived  pclass     sex   age  sibsp  parch     fare embarked   class  \
14          0       3  female  14.0      0      0   7.8542        S   Third   
16          0       3    male   2.0      4      1  29.1250        Q   Third   
17          1       2    male   NaN      0      0  13.0000        S  Second   
20          0       2    male  35.0      0      0  26.0000        S  Second   
25          1       3  female  38.0      1      5  31.3875        S   Third   
..        ...     ...     ...   ...    ...    ...      ...      ...     ...   
886         0       2    male  27.0      0      0  13.0000        S  Second   
887         1       1  female  19.0      0      0  30.0000        S   First   
888         0       3  female   NaN      1      2  23.4500        S   Third   
889         1       1    male  26.0      0      0  30.0000        C   First   
890         0       3    male  32.0      0      0   7.7500        Q   Third   

       who  adult_male deck  embark_town alive  alone  
14   child       False  NaN  Southampton    no   True  
16   child       False  NaN   Queenstown    no  False  
17     man        True  NaN  Southampton   yes   True  
20     man        True  NaN  Southampton    no   True  
25   woman       False  NaN  Southampton   yes  False  
..     ...         ...  ...          ...   ...    ...  
886    man        True  NaN  Southampton    no   True  
887  woman       False    B  Southampton   yes   True  
888  woman       False  NaN  Southampton    no  False  
889    man        True    C    Cherbourg   yes   True  
890    man        True  NaN   Queenstown    no   True  

[744 rows x 15 columns]

# Outliers

Detectoin

In [24]:
df.describe().round(2)

survived  pclass     age   sibsp   parch    fare
count    891.00  891.00  714.00  891.00  891.00  891.00
mean       0.38    2.31   29.70    0.52    0.38   32.20
std        0.49    0.84   14.53    1.10    0.81   49.69
min        0.00    1.00    0.42    0.00    0.00    0.00
25%        0.00    2.00   20.12    0.00    0.00    7.91
50%        0.00    3.00   28.00    0.00    0.00   14.45
75%        1.00    3.00   38.00    1.00    0.00   31.00
max        1.00    3.00   80.00    8.00    6.00  512.33

In [25]:
sns.boxplot

<function seaborn.categorical.boxplot(*, x=None, y=None, hue=None, data=None, order=None, hue_order=None, orient=None, color=None, palette=None, saturation=0.75, width=0.8, dodge=True, fliersize=5, linewidth=None, whis=1.5, ax=None, **kwargs)>

In [26]:
q1=df['fare'].quantile(0.25)
q1

7.9104

In [27]:
q3=df['fare'].quantile(0.75)
q3

31.0

In [28]:
iqr=q3-q1
iqr

23.0896

In [29]:
x=q1+1.5*iqr
x

42.5448

In [30]:
l=q1-1.5*iqr
l

-26.724

In [31]:
df.sample()
df['sex'].value_counts()

male      577
female    314
Name: sex, dtype: int64

## One Hot Encoding


In [32]:
pd.get_dummies(df['sex'])

female  male
0         0     1
1         1     0
2         1     0
3         1     0
4         0     1
..      ...   ...
886       0     1
887       1     0
888       1     0
889       0     1
890       0     1

[891 rows x 2 columns]

In [33]:
df['M']=pd.get_dummies(df['sex'],drop_first=True)
df

survived  pclass     sex   age  sibsp  parch     fare embarked   class  \
0           0       3    male  22.0      1      0   7.2500        S   Third   
1           1       1  female  38.0      1      0  71.2833        C   First   
2           1       3  female  26.0      0      0   7.9250        S   Third   
3           1       1  female  35.0      1      0  53.1000        S   First   
4           0       3    male  35.0      0      0   8.0500        S   Third   
..        ...     ...     ...   ...    ...    ...      ...      ...     ...   
886         0       2    male  27.0      0      0  13.0000        S  Second   
887         1       1  female  19.0      0      0  30.0000        S   First   
888         0       3  female   NaN      1      2  23.4500        S   Third   
889         1       1    male  26.0      0      0  30.0000        C   First   
890         0       3    male  32.0      0      0   7.7500        Q   Third   

       who  adult_male deck  embark_town alive  alone  M  
0      man        True  NaN  Southampton    no  False  1  
1    woman       False    C    Cherbourg   yes  False  0  
2    woman       False  NaN  Southampton   yes   True  0  
3    woman       False    C  Southampton   yes  False  0  
4      man        True  NaN  Southampton    no   True  1  
..     ...         ...  ...          ...   ...    ... ..  
886    man        True  NaN  Southampton    no   True  1  
887  woman       False    B  Southampton   yes   True  0  
888  woman       False  NaN  Southampton    no  False  0  
889    man        True    C    Cherbourg   yes   True  1  
890    man        True  NaN   Queenstown    no   True  1  

[891 rows x 16 columns]

In [34]:
pd.get_dummies(df['sex'],drop_first=True)

male
0       1
1       0
2       0
3       0
4       1
..    ...
886     1
887     0
888     0
889     1
890     1

[891 rows x 1 columns]

In [35]:
from sklearn.preprocessing import OneHotEncoder

In [36]:
enc=OneHotEncoder()

In [37]:
enc.fit_transform(df[['sex']]).toarray()

array([[0., 1.],
       [1., 0.],
       [1., 0.],
       ...,
       [1., 0.],
       [0., 1.],
       [0., 1.]])

In [38]:
df['class'].value_counts()

Third     491
First     216
Second    184
Name: class, dtype: int64

In [39]:
enc.fit_transform(df[['class']]).toarray()

array([[0., 0., 1.],
       [1., 0., 0.],
       [0., 0., 1.],
       ...,
       [0., 0., 1.],
       [1., 0., 0.],
       [0., 0., 1.]])

In [40]:
pd.DataFrame(enc.fit_transform(df))

0
0      (0, 0)\t1.0\n  (0, 4)\t1.0\n  (0, 6)\t1.0\n ...
1      (0, 1)\t1.0\n  (0, 2)\t1.0\n  (0, 5)\t1.0\n ...
2      (0, 1)\t1.0\n  (0, 4)\t1.0\n  (0, 5)\t1.0\n ...
3      (0, 1)\t1.0\n  (0, 2)\t1.0\n  (0, 5)\t1.0\n ...
4      (0, 0)\t1.0\n  (0, 4)\t1.0\n  (0, 6)\t1.0\n ...
..                                                 ...
886    (0, 0)\t1.0\n  (0, 3)\t1.0\n  (0, 6)\t1.0\n ...
887    (0, 1)\t1.0\n  (0, 2)\t1.0\n  (0, 5)\t1.0\n ...
888    (0, 0)\t1.0\n  (0, 4)\t1.0\n  (0, 5)\t1.0\n ...
889    (0, 1)\t1.0\n  (0, 2)\t1.0\n  (0, 6)\t1.0\n ...
890    (0, 0)\t1.0\n  (0, 4)\t1.0\n  (0, 6)\t1.0\n ...

[891 rows x 1 columns]

In [41]:
pd.get_dummies(df['class'])

First  Second  Third
0        0       0      1
1        1       0      0
2        0       0      1
3        1       0      0
4        0       0      1
..     ...     ...    ...
886      0       1      0
887      1       0      0
888      0       0      1
889      1       0      0
890      0       0      1

[891 rows x 3 columns]

###  Label Encoding

In [42]:
from sklearn.preprocessing import LabelEncoder

In [43]:
enc=LabelEncoder()

In [44]:
enc.fit_transform(df[['class']])

C:\Users\Acer\Downloads\epslion\myaana\lib\site-packages\sklearn\preprocessing\_label.py:115: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)


array([2, 0, 2, 0, 2, 2, 0, 2, 2, 1, 2, 0, 2, 2, 2, 1, 2, 1, 2, 2, 1, 1,
       2, 0, 2, 2, 2, 0, 2, 2, 0, 0, 2, 1, 0, 0, 2, 2, 2, 2, 2, 1, 2, 1,
       2, 2, 2, 2, 2, 2, 2, 2, 0, 1, 0, 0, 1, 2, 1, 2, 2, 0, 0, 2, 0, 2,
       1, 2, 2, 2, 1, 2, 1, 2, 2, 2, 2, 2, 1, 2, 2, 2, 2, 0, 1, 2, 2, 2,
       0, 2, 2, 2, 0, 2, 2, 2, 0, 0, 1, 1, 2, 2, 0, 2, 2, 2, 2, 2, 2, 2,
       0, 2, 2, 2, 2, 2, 2, 1, 0, 2, 1, 2, 1, 1, 0, 2, 2, 2, 2, 2, 2, 2,
       2, 1, 1, 1, 0, 0, 2, 0, 2, 2, 2, 2, 1, 1, 2, 2, 1, 1, 1, 0, 2, 2,
       2, 0, 2, 2, 2, 2, 2, 1, 2, 2, 2, 2, 0, 2, 0, 2, 0, 2, 2, 2, 0, 2,
       2, 0, 1, 2, 2, 1, 2, 1, 2, 0, 2, 0, 2, 2, 1, 1, 2, 1, 0, 0, 2, 2,
       2, 1, 2, 2, 2, 2, 2, 2, 2, 2, 2, 0, 2, 1, 2, 1, 2, 0, 2, 1, 0, 1,
       2, 1, 2, 2, 0, 2, 1, 2, 1, 2, 0, 2, 1, 2, 1, 2, 1, 1, 1, 1, 2, 2,
       1, 2, 2, 0, 2, 1, 0, 1, 2, 2, 0, 2, 2, 2, 0, 0, 0, 1, 2, 2, 0, 0,
       2, 1, 2, 2, 0, 0, 0, 2, 1, 0, 2, 0, 2, 1, 2, 2, 2, 2, 2, 2, 0, 2,
       2, 2, 1, 2, 0, 0, 1, 2, 2, 0, 2, 0, 0, 0, 2,

In [45]:
df['my_class']=enc.fit_transform(df[['class']])

C:\Users\Acer\Downloads\epslion\myaana\lib\site-packages\sklearn\preprocessing\_label.py:115: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)


In [46]:
df

survived  pclass     sex   age  sibsp  parch     fare embarked   class  \
0           0       3    male  22.0      1      0   7.2500        S   Third   
1           1       1  female  38.0      1      0  71.2833        C   First   
2           1       3  female  26.0      0      0   7.9250        S   Third   
3           1       1  female  35.0      1      0  53.1000        S   First   
4           0       3    male  35.0      0      0   8.0500        S   Third   
..        ...     ...     ...   ...    ...    ...      ...      ...     ...   
886         0       2    male  27.0      0      0  13.0000        S  Second   
887         1       1  female  19.0      0      0  30.0000        S   First   
888         0       3  female   NaN      1      2  23.4500        S   Third   
889         1       1    male  26.0      0      0  30.0000        C   First   
890         0       3    male  32.0      0      0   7.7500        Q   Third   

       who  adult_male deck  embark_town alive  alone  M  my_class  
0      man        True  NaN  Southampton    no  False  1         2  
1    woman       False    C    Cherbourg   yes  False  0         0  
2    woman       False  NaN  Southampton   yes   True  0         2  
3    woman       False    C  Southampton   yes  False  0         0  
4      man        True  NaN  Southampton    no   True  1         2  
..     ...         ...  ...          ...   ...    ... ..       ...  
886    man        True  NaN  Southampton    no   True  1         1  
887  woman       False    B  Southampton   yes   True  0         0  
888  woman       False  NaN  Southampton    no  False  0         2  
889    man        True    C    Cherbourg   yes   True  1         0  
890    man        True  NaN   Queenstown    no   True  1         2  

[891 rows x 17 columns]

### Binary Encoding

In [47]:
from sklearn.preprocessing import LabelBinarizer

In [48]:
enc=LabelBinarizer()

In [49]:
enc.fit_transform(df[['class']])

array([[0, 0, 1],
       [1, 0, 0],
       [0, 0, 1],
       ...,
       [0, 0, 1],
       [1, 0, 0],
       [0, 0, 1]])

In [50]:
pip install category_encoders 


Note: you may need to restart the kernel to use updated packages.


In [51]:
import category_encoders as ce

In [52]:
ce.BinaryEncoder()


BinaryEncoder()

In [53]:
enc=ce.BinaryEncoder()

In [54]:
enc.fit_transform(df[['class']])

class_0  class_1
0          0        1
1          1        0
2          0        1
3          1        0
4          0        1
..       ...      ...
886        1        1
887        1        0
888        0        1
889        1        0
890        0        1

[891 rows x 2 columns]